### ISSUE TITLE
Any ideas to implement complex authorization logic

### ISSUE THREAD

**Issue by lavilaso** [iammukeshm/CleanArchitecture.WebApi#12]
I need to implement complex authorization logic, normally I would solve this using Identity policies, in this architecture I don't know what would be a good way to implement this.
policies in the project for identity?
use validations in MediatR behaviorss?
Let me know your thoughts.

**Comment by iammukeshm** [comment]
Yes Policies Would be the way forward. I already have it in my TODO list. Will update shortly
