### ISSUE TITLE
Upgrade to .NET 5

### ISSUE THREAD

**Issue by emmysteven** [iammukeshm/CleanArchitecture.WebApi#26]
**Is your feature request related to a problem? Please describe.**
It would nice for the project to be upgraded to .NET 5

**Describe the solution you'd like**
I could help with upgrading the project .NET 5 and then create a pull request. I just wanted to discuss it here first.

**Describe alternatives you've considered**
None at the moment

**Additional context**
No additional context at the moment

**Comment by iammukeshm** [comment]
Yes, this project is being currently developed for 5.0 in another repository. Will be released in a month. 
https://github.com/coreboilerplate/coreboilerplate
