### ISSUE TITLE
Serilog dont logging

### ISSUE THREAD

**Issue by NurdaKz** [iammukeshm/CleanArchitecture.WebApi#31]
After this line in Program.cs, nothing is logged 

https://github.com/iammukeshm/CleanArchitecture.WebApi/blob/4d89c2c5fc0cf79b71995ac11d9b6d828ead7d7e/WebApi/Program.cs#L54

**Comment by alydemah** [comment]
Had the same issue, you need to move this line inside try catch block in Program.cs



```
  try
   {

 ///..... Other code
await host.RunAsync();


}


```

**Comment by virux99** [comment]
> Had the same issue, you need to move this line inside try catch block in Program.cs
> 
> ```
>   try
>    {
> 
>  ///..... Other code
> await host.RunAsync();
> 
> 
> }
> ```

thanks @alydemah this solved the issue
