### ISSUE TITLE
Unrecognized option '-Context' when running dotnet ef command

### ISSUE THREAD

**Issue by lukeconner** [iammukeshm/CleanArchitecture.WebApi#4]
**Describe the bug**
When following the commands to install, after dotnet restore it gives the error Unrocognized option '-Context'

**To Reproduce**
1. Clone Project
2. Change connection string
3. Run dotnet restore
4. Run dotnet-ef database update -Context ApplicationDbContext

**Expected behavior**
I expected it would create the tables

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 3.1 SDK installed

**Comment by lukeconner** [comment]
I have no idea why this is an issue, but using -c instead of -Context resolved the issue.

**Comment by iammukeshm** [comment]
That's weird. Is your ef code updated to the latest version?

**Comment by lukeconner** [comment]
Yeah, I reinstalled the SDK just to be sure.  Likely it's something with my local setup.

**Comment by khaledafify** [comment]
`dotnet-ef database update -c ApplicationDbContext
`
it will fix the problem
