### ISSUE TITLE
how support other databases,eg:mysql

### ISSUE THREAD

**Issue by newpost** [iammukeshm/CleanArchitecture.WebApi#6]

**Comment by iammukeshm** [comment]
Currently we are using MSSQL. If you want to switch over to another RDBMS, Simply install the related package of EFCOre -  'MySql.Data.EntityFrameworkCore' on your Persitence Layer and configure your appsettings accordingly. It's pretty easy with this approach in architecture.

**Comment by lemchen** [comment]
Simply install the related package of EFCore is not work.  dotnet ef migrations  not work.
