### ISSUE TITLE
How to add redis caching support?

### ISSUE THREAD

**Issue by lemchen** [iammukeshm/CleanArchitecture.WebApi#8]
How to add redis caching support? It is just simplely add some redis code to Controller in webapi?

**Comment by iammukeshm** [comment]
You do not want to add any redis code to the controller. It's advisable to move the redis cache calls to the application layer within the MediatR implementations. It would be a cleaner fit.

Also, here is a post on Redis Caching - https://www.codewithmukesh.com/blog/redis-caching-in-aspnet-core/

**Comment by lemchen** [comment]
Thanks for your suggestion
