### ISSUE TITLE
Adding multiple authentication providers

### ISSUE THREAD

**Issue by pdevito3** [iammukeshm/CleanArchitecture.WebApi#9]
**Describe the solution you'd like**
Any thoughts on adding multiple authentication providers (e.g. Facebook, Google, Github, MS, Auth0, Okta, etc.)?

**Describe alternatives you've considered**
Currently researching how to add these, but don't have a ton of experience on the Auth side of things.

**Comment by iammukeshm** [comment]
While designing this solution, I didnt have social auth in mind. However, it is do-able, not with this kind of dedicated auth. We will need to user Auth0 like Identity Server 4 , which may introduce it's own level of complexity. I will add IS4 to my list as well. Thanks
